[[plugins]]
repo = 'Shougo/denite.nvim'
if = '!exists("veonim")'
on_event = "VimEnter"
hook_add = """
nnoremap <silent> <C-p> :<C-u>Denite file/rec -highlight-mode-insert=Search<CR>
nnoremap <silent> ,m :<C-u>Denite file/mru -highlight-mode-insert=Search<CR>
nnoremap <silent> ,g :<C-u>Denite -auto_preview grep -highlight-mode-insert=Search<CR>
nnoremap <silent> ,wg :<C-u>DeniteCursorWord -auto_preview grep -highlight-mode-insert=Search<CR>
nnoremap <silent> ,r :<C-u>Denite -resume -highlight-mode-insert=Search<CR>
nnoremap <silent> ,c :<C-u>Denite ghq -default-action=cd -highlight-mode-insert=Search<CR>
"""

hook_post_source = """
call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])

call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')

let s:denite_win_width_percent = 0.8
let s:denite_win_height_percent = 0.6

" Change denite default options
call denite#custom#option('default', {
    \ 'split': 'floating',
    \ 'winwidth': &columns * s:denite_win_width_percent,
    \ 'wincol': (&columns - (&columns * s:denite_win_width_percent)) / 2,
    \ 'winheight': &lines * s:denite_win_height_percent,
    \ 'winrow': (&lines - (&lines * s:denite_win_height_percent)) / 2,
    \ })
"""

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = ['denite.nvim']

[[plugins]]
repo ="majutsushi/tagbar"
on_event = "VimEnter"

[[plugins]]
if = '!exists("veonim")'
repo = "cohama/lexima.vim"
on_event = "InsertEnter"

[[plugins]]
repo = 'lervag/vimtex'
on_ft = "tex"
hook_source = '''
let g:vimtex_fold_envs = 0
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \ ]}
let g:vimtex_compiler_progname = 'nvr'
let g:tex_conceal = ''
'''

[[plugins]]
repo = "iamcco/markdown-preview.vim"
on_ft = "markdown"

[[plugins]]
repo = "mattn/emmet-vim"
on_ft = ["html", "vue", "markdown", "javascript"]
hook_add = """
let g:user_emmet_settings = {'variables':{'lang' : 'ja'}}
let g:user_emmet_leader_key = '<C-l>'
"""

[[plugins]]
repo = "simeji/winresizer"
on_map = ["<C-e>"]
hook_add = """
let g:winresizer_vert_resize=5
"""

[[plugins]]
repo = "tyru/current-func-info.vim"
on_event = "BufReadPost"

[[plugins]]
if = '!exists("veonim")'
repo = "fatih/vim-go"
on_ft = "go"
hook_post_update = """
:GoInstallBinaries
"""
hook_add = """
let g:go_term_enabled = 0
let g:go_term_mode = "botright split"
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 0
let g:go_fmt_autosave = 1
let g:go_doc_keywordprg_enabled = 0
let g:go_jump_to_error = 0
let g:go_auto_type_info = 1
let g:go_auto_sameids = 1

let g:go_info_mode = 'guru'
let g:go_gocode_unimported_packages = 1
"""

[[plugins]]
repo = "scrooloose/nerdtree"
on_cmd = ["NERDTreeToggle", "NERDTree"]
hook_add = """
let g:NERDTreeShowHidden = 1
let g:NERDTreeShowBookmarks = 1
let g:NERDTreeShowLineNumbers = 0
let g:NERDTreeHighlightCursorline = 1
let g:NERDTreeWinSize = 24
let g:NERDTreeChDirMode = 2

" フォルダアイコンの表示をON
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
"""

[[plugins]]
on_map = "<Space>"
repo = "airblade/vim-gitgutter"

[[plugins]]
on_map = "<Space>"
repo = "cohama/agit.vim"
hook_add = """
noremap <Space>gv :Agit<CR>
"""

[[plugins]]
repo = 'buoto/gotests-vim'
on_ft = 'go'
