[[plugins]]
repo = "cohama/lexima.vim"
on_event = "InsertEnter"

[[plugins]]
repo = "mattn/emmet-vim"
on_ft = ["html", "vue", "markdown", "javascript"]
hook_add = """
let g:user_emmet_settings = {'variables':{'lang' : 'ja'}}
let g:user_emmet_leader_key = '<C-l>'
"""

[[plugins]]
repo = "simeji/winresizer"
on_map = ["<C-e>"]
hook_add = """
let g:winresizer_vert_resize=5
"""


[[plugins]]
repo = "scrooloose/nerdtree"
on_cmd = ["NERDTreeToggle", "NERDTree"]
hook_add = """
let g:NERDTreeShowHidden = 1
let g:NERDTreeShowBookmarks = 1
let g:NERDTreeShowLineNumbers = 0
let g:NERDTreeHighlightCursorline = 1
let g:NERDTreeWinSize = 24
let g:NERDTreeChDirMode = 2

" フォルダアイコンの表示をON
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
"""

[[plugins]]
on_map = "<Space>"
repo = "airblade/vim-gitgutter"

[[plugins]]
on_map = "<Space>"
repo = "cohama/agit.vim"
hook_add = """
noremap <Space>gv :Agit<CR>
"""

