# frozen_string_literal: true
source "https://rubygems.org"
gem 'itamae'
gem 'itamae-plugin-resource-authorized_keys'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
